name: Build
on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.x"
            - name: Display dotnet version
              run: dotnet --version
            - name: Install dependencies
              run: dotnet restore Miberr.CalculateRollup.csproj
            - name: Build
              run: dotnet build Miberr.CalculateRollup.csproj --no-restore
